version: "3.8"

services:
    ingress-nginx:
        image: nginx:1.25
        ports:
            - "80:80"
        volumes:
            - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - auth-service
            - items-service
            - bidding-service

    auth-service:
        build: ./services/auth-service
        env_file: ./services/auth-service/.env
        volumes:
            - ./services/auth-service:/usr/src/app
            - /usr/src/app/node_modules
        command: >
            sh -c "npx sequelize-cli db:migrate && npm start"
        depends_on:
            postgres-auth-db:
                condition: service_healthy
    
    items-service:
        build: ./services/items-service
        env_file: ./services/items-service/.env
        volumes:
        - ./services/items-service:/usr/src/app
        - /usr/src/app/node_modules
        command: >
            sh -c "npx sequelize-cli db:migrate && npm start"
        depends_on:
            postgres-items-db:
                condition: service_healthy
    bidding-service: 
        build: ./services/bidding-service
        env_file: ./services/bidding-service/.env
        volumes:
        - ./services/bidding-service:/usr/src/app
        - /usr/src/app/node_modules
        command: >
            sh -c "npx sequelize-cli db:migrate && npm start"
        depends_on:
            postgres-bids-db:
                condition: service_healthy
    postgres-auth-db:
        image: postgres:15
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=secret_password
            - POSTGRES_DB=auth_db
        ports:
            - "5432:5432"
        volumes:
            - auth_db_data:/var/lib/postgresql/data # This line makes data persistent
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d auth_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    postgres-items-db:  
        image: postgres:15
        environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=secret_password
        - POSTGRES_DB=items_db
        ports:
            - "5433:5432" # Use a different host port (5433)
        volumes:
            - items_db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d items_db"]
            interval: 10s
            timeout: 5s
            retries: 5

    minio: 
        image: minio/minio:latest
        ports:
        - "9000:9000" # API Port
        - "9001:9001" # Console UI Port
        volumes:
        - minio_data:/data
        environment:
        - MINIO_ROOT_USER=minioadmin
        - MINIO_ROOT_PASSWORD=minioadmin
        command: server /data --console-address ":9001"

    postgres-bids-db: 
        image: postgres:15
        environment:
        - POSTGRES_USER=admin
        - POSTGRES_PASSWORD=secret_password
        - POSTGRES_DB=bids_db
        ports:
        - "5434:5432" 
        volumes:
        - bids_db_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U admin -d bids_db"]
            interval: 10s
            timeout: 5s
            retries: 5
# Top-level key to define the named volume
volumes:
    auth_db_data:
    items_db_data:
    minio_data:
    bids_db_data: