apiVersion: apps/v1
kind: Deployment
metadata:
  name: bidding-service
  namespace: campus-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bidding-service
  template:
    metadata:
      labels:
        app: bidding-service
    spec:
      containers:
        - name: bidding-service
          image: bidding-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5003
          envFrom:
            - secretRef:
                name: bidding-service-secret
          env:
            - name: KAFKA_BROKER
              value: kafka-service.campus-shop.svc.cluster.local:9092
            - name: AUTH_SERVICE_URL
              value: http://auth-service.campus-shop.svc.cluster.local
            - name: ITEMS_SERVICE_URL
              value: http://items-service.campus-shop.svc.cluster.local
            - name: BIDDING_SERVICE_URL
              value: http://bidding-service.campus-shop.svc.cluster.local
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Postgres to be ready...";
              echo "Running migrations...";
              npx sequelize-cli db:migrate;
              echo "Starting app...";
              npm start;
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: bidding-service
  namespace: campus-shop
spec:
  ports:
    - port: 80
      targetPort: 5003
  selector:
    app: bidding-service
