apiVersion: apps/v1
kind: Deployment
metadata:
  name: items-service
  namespace: campus-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items-service
  template:
    metadata:
      labels:
        app: items-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5002"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: items-service
          image: items-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5002
          envFrom:
            - secretRef:
                name: items-service-secret
          env:
            - name: MINIO_BUCKET
              value: campusshop-items
            - name: AUTH_SERVICE_URL
              value: http://auth-service.campus-shop.svc.cluster.local
            - name: ITEMS_SERVICE_URL
              value: http://items-service.campus-shop.svc.cluster.local
            - name: BIDDING_SERVICE_URL
              value: http://bidding-service.campus-shop.svc.cluster.local
          command: ["/bin/sh", "-c"]
          args:
            - |
              npx sequelize-cli db:migrate;
              npm start;  
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: items-service
  namespace: campus-shop
spec:
  ports:
    - port: 80
      targetPort: 5002
  selector:
    app: items-service
