apiVersion: apps/v1
kind: Deployment
metadata:
  name: profile-service
  namespace: campus-shop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: profile-service
  template:
    metadata:
      labels:
        app: profile-service
    spec:
      containers:
        - name: profile-service
          image: profile-service:local
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5005
          envFrom:
            - secretRef:
                name: profile-service-secret
          env:
            - name: AUTH_SERVICE_URL
              value: http://auth-service.campus-shop.svc.cluster.local
            - name: ITEMS_SERVICE_URL
              value: http://items-service.campus-shop.svc.cluster.local
            - name: BIDDING_SERVICE_URL
              value: http://bidding-service.campus-shop.svc.cluster.local
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Waiting for Postgres to be ready...";
              echo "Running migrations...";
              npx sequelize-cli db:migrate;
              echo "Starting app...";
              npm start;
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: profile-service
  namespace: campus-shop
spec:
  ports:
    - port: 80
      targetPort: 5005
  selector:
    app: profile-service
